# Generated by Django 4.0.3 on 2022-03-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_district_maritalstatus_state_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
